### ISSUE TITLE
Categories Deploy Checklist

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/Apiary#146]
## TODO
- [x] don't allow skipped indices to initialize for Word Lists, log appropriately
- [x] IAP popup should only appear for users who haven't already purchased
- [x] speed round check / intermission
- [x] add obscurity to algorithm
- [x] modals / events
- [x] free words configurable from backend
- [x] everything category features
- [x] speed up transitions
- [x] review round
- [x] block users after free version finished
- [x] send to Firebase `fullVersionUnlocked`,  ideally:`categories/rounds played`, `searchAdsAttribution`, any geotagging possible

## Bugs
- [x] On first open words aren't related to categories (high priority fix)
- [x] Crashing on double tap a picture (edge case probably), crashing after picture sometimes
- [x] Click next round (Everything) crash
- [x] Word completing (insecticide) too fast

## Growth
- [x] share word PR
- [x] refer a friend

## UX 
- [x] remove age pick screen - BB
- [x] If we're not putting all words on category screen, +25 words should go to the right - BB
- [x] Tapping the back button on the Words should take you the page before, not just the main page - BB
- [x] add label for word mastery on stats vc BB (mastered = starCount > 7, learned = seenCount > 0)
- [x] colors for rest of categories
- [x] Tapping Word Metrics Rectangle in category should take you to words too - BB
- [x]  Gradient on category pages with that category color at 20% opacity - BB
- [x] Bold words learned / words mastered - BB

**Comment by OLI9292** [comment]
Add: level collection view overlapping text
